### ISSUE TITLE
issue with comments

### ISSUE THREAD

**Issue by frigaut** [akshay-joshi/redmine2github#1]
Hello there,

I am trying to make use of your redmine2github. Thanks for putting that online.
I have had a number of issues with pygithub3 (may be more on that later).
The latest, that I don't know how to solve is that pygithub3 is (in gist) trying to make use of the comments package, but I get an error:
```
Traceback (most recent call last):
  File "/home/frigaut/projects/planio_migration/redmine2github/src/github_issues/migration_manager.py", line 259, in <module>
    mm.migrate_issues()
  File "/home/frigaut/projects/planio_migration/redmine2github/src/github_issues/migration_manager.py", line 181, in migrate_issues
    gm = GithubIssueMaker(
  File "/home/frigaut/projects/planio_migration/redmine2github/src/github_issues/github_issue_maker.py", line 48, in __init__
    self.milestone_manager = MilestoneHelper(milestone_mapping_filename)
  File "/home/frigaut/projects/planio_migration/redmine2github/src/github_issues/milestone_helper.py", line 59, in __init__
    self.get_github_conn()
  File "/home/frigaut/projects/planio_migration/redmine2github/src/github_issues/milestone_helper.py", line 98, in get_github_conn
    self.github_conn = pygithub3.Github(**get_github_auth())
  File "/home/frigaut/.virtualenvs/redmine_move/lib/python3.9/site-packages/pygithub3/github.py", line 19, in __init__
    from pygithub3.services.gists import Gist
  File "/home/frigaut/.virtualenvs/redmine_move/lib/python3.9/site-packages/pygithub3/services/gists/__init__.py", line 5, in <module>
    from comments import Comments
ImportError: cannot import name 'Comments' from 'comments' (/home/frigaut/.virtualenvs/redmine_move/lib/python3.9/site-packages/comments/__init__.py)
(redmine_move) [frigaut@archbox github_issues]$  
```
Any idea what package I have to install? I have installed "comments" from pip, but to no avail:
```
(redmine_move) [frigaut@archbox github_issues]$ pip install comments
Collecting comments
  Downloading comments-1.0.0.tar.gz (2.4 kB)
Requirement already satisfied: urllib3 in /home/frigaut/.virtualenvs/redmine_move/lib/python3.9/site-packages (from comments) (1.26.7)
Requirement already satisfied: certifi in /home/frigaut/.virtualenvs/redmine_move/lib/python3.9/site-packages (from comments) (2021.5.30)
Building wheels for collected packages: comments
  Building wheel for comments (setup.py) ... done
  Created wheel for comments: filename=comments-1.0.0-py3-none-any.whl size=2986 sha256=c224cbdba0616e50f1d247354e651b4e98c8af7d3f5cd2b057591c5b9abc50b4
  Stored in directory: /home/frigaut/.cache/pip/wheels/43/12/ee/28719d49baed1a126a4b18295325a6c32877cf2d9209e4efce
Successfully built comments
Installing collected packages: comments
Successfully installed comments-1.0.0
(redmine_move) [frigaut@archbox github_issues]$ python 
Python 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import comments
>>> from comments import Comments
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Comments' from 'comments' (/home/frigaut/.virtualenvs/redmine_move/lib/python3.9/site-packages/comments/__init__.py)
```
Thanks.

**Comment by akshay-joshi** [comment]
I haven't face the above issue on OSX catalina. I created the virtual environment, activate that using "source <absolute path>bin/activate" and then run "pip install -r requirements/base.txt" 

The above works for me.

**Comment by frigaut** [comment]
OK - I will give it a try on macos.
